services:
  mock-server:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: mock-server
    ports:
      - '8090:8090'
    environment:
      - APP_URL=http://localhost:3000
      - MOCK_API_PORT=8090
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run mock-server

  app:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: app
    ports:
      - '3000:3000'
    environment:
      - APP_URL=http://localhost:3000
      - API_URL=http://mock-server:8090/api
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - mock-server
